//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace www.flymsg.com.context
{
    using System;
    using System.Collections.Generic;
    
    public partial class IpLog
    {
        public int Id { get; set; }
        public Nullable<int> GameId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Ip { get; set; }
        public string ActionUrl { get; set; }
        public string ClientUrl { get; set; }
        public string UrlReferrer { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> CreateUser { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<int> UpdateUser { get; set; }
    }
}
