//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace www.flymsg.com.context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SiteGameEntities : DbContext
    {
        public SiteGameEntities()
            : base("name=SiteGameEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Evaluation> Evaluation { get; set; }
        public virtual DbSet<Game> Game { get; set; }
        public virtual DbSet<GameBBS> GameBBS { get; set; }
        public virtual DbSet<GameType> GameType { get; set; }
        public virtual DbSet<IpLog> IpLog { get; set; }
        public virtual DbSet<PageTitleLink> PageTitleLink { get; set; }
        public virtual DbSet<SiteUser> SiteUser { get; set; }
        public virtual DbSet<V_GamesOrder> V_GamesOrder { get; set; }
        public virtual DbSet<V_UsersGames> V_UsersGames { get; set; }
        public virtual DbSet<EvaluationDay> EvaluationDay { get; set; }
        public virtual DbSet<EvaluationMonth> EvaluationMonth { get; set; }
        public virtual DbSet<EvaluationWeek> EvaluationWeek { get; set; }
    
        [DbFunction("SiteGameEntities", "f_splitSTR")]
        public virtual IQueryable<string> f_splitSTR(string s, string split)
        {
            var sParameter = s != null ?
                new ObjectParameter("s", s) :
                new ObjectParameter("s", typeof(string));
    
            var splitParameter = split != null ?
                new ObjectParameter("split", split) :
                new ObjectParameter("split", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<string>("[SiteGameEntities].[f_splitSTR](@s, @split)", sParameter, splitParameter);
        }
    }
}
