//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace www.flymsg.com.context
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteUser
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Sex { get; set; }
        public string Telephone { get; set; }
        public string Email { get; set; }
        public Nullable<int> ULevel { get; set; }
        public string LoginName { get; set; }
        public string Passwork { get; set; }
        public Nullable<int> IsVisible { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> CreateUser { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<int> UpdateUser { get; set; }
    }
}
