//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace www.flymsg.com.context
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_GamesOrder
    {
        public int Id { get; set; }
        public Nullable<int> GameId { get; set; }
        public Nullable<int> ClientCount { get; set; }
        public Nullable<int> VisitCount { get; set; }
        public Nullable<int> Eat { get; set; }
        public string SmallImage { get; set; }
        public int Expr1 { get; set; }
        public string BigImage { get; set; }
        public Nullable<int> OrderNum { get; set; }
        public string Anthor { get; set; }
        public string GamePath { get; set; }
        public string Title { get; set; }
        public string OperationType { get; set; }
        public string Intro { get; set; }
        public string Label { get; set; }
        public string GameType { get; set; }
        public string Backup { get; set; }
        public Nullable<int> IsVisible { get; set; }
        public string Name { get; set; }
        public string IconCss { get; set; }
    }
}
