//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace www.flymsg.com.context
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_UsersGames
    {
        public Nullable<int> Id { get; set; }
        public string Name { get; set; }
        public string IconCss { get; set; }
        public string SmallImage { get; set; }
        public string BigImage { get; set; }
        public Nullable<int> OrderNum { get; set; }
        public string GamePath { get; set; }
        public Nullable<int> ContentLength { get; set; }
        public string Anthor { get; set; }
        public string Title { get; set; }
        public string OperationType { get; set; }
        public string Intro { get; set; }
        public string Label { get; set; }
        public string GameType { get; set; }
        public string Backup { get; set; }
        public Nullable<int> IsVisible { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> CreateUser { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<int> UpdateUser { get; set; }
        public Nullable<int> UserId { get; set; }
        public int IpId { get; set; }
    }
}
